[phases.setup]
nixPkgs = ["...", "openssl", "gcc", "sqlite"]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bunx prisma generate", "bunx next build", "mkdir -p .next/standalone/.next", "cp -r .next/static .next/standalone/.next/", "cp -r public .next/standalone/"]

[phases.start]
cmd = "cd .next/standalone && node server.js"

[variables]
NODE_ENV = "production"
DATABASE_URL = "file:/data/custom.db"
PORT = "3000"
